#ifndef LE_KEYCODES_H_
#define LE_KEYCODES_H_

#pragma once

#include <cstdint>

#include <Windows.h>

namespace Lightning3D::Engine {
    enum struct LE_KEYCODE : uint32_t {
        LE_KC_BACK              = VK_BACK,
        LE_KC_TAB               = VK_TAB,
        LE_KC_CLEAR             = VK_CLEAR,
        LE_KC_ENTER             = VK_RETURN,
        LE_KC_SHIFT             = VK_SHIFT,
        LE_KC_CTRL              = VK_CONTROL,
        LE_KC_ALT               = VK_MENU,
        LE_KC_PAUSE             = VK_PAUSE,
        LE_KC_CAPSLOCK          = VK_CAPITAL,
        LE_KC_ESCAPE            = VK_ESCAPE,
        LE_KC_SPACE             = VK_SPACE,
        LE_KC_PAGEUP            = VK_PRIOR,
        LE_KC_PAGEDOWN          = VK_NEXT,
        LE_KC_END               = VK_END,
        LE_KC_HOME              = VK_HOME,
        LE_KC_LEFT              = VK_LEFT,
        LE_KC_UP                = VK_UP,
        LE_KC_RIGHT             = VK_RIGHT,
        LE_KC_DOWN              = VK_DOWN,
        LE_KC_SELECT            = VK_SELECT,
        LE_KC_PRINT             = VK_PRINT,
        LE_KC_EXECUTE           = VK_EXECUTE,
        LE_KC_PRINTSCREEN       = VK_SNAPSHOT,
        LE_KC_INSERT            = VK_INSERT,
        LE_KC_DELETE            = VK_DELETE,
        LE_KC_HELP              = VK_HELP,
        LE_KC_0                 = 0x30,
        LE_KC_1                 = 0x31,
        LE_KC_2                 = 0x32,
        LE_KC_3                 = 0x33,
        LE_KC_4                 = 0x34,
        LE_KC_5                 = 0x35,
        LE_KC_6                 = 0x36,
        LE_KC_7                 = 0x37,
        LE_KC_8                 = 0x38,
        LE_KC_9                 = 0x39,
        LE_KC_A                 = 0x41,
        LE_KC_B                 = 0x42,
        LE_KC_C                 = 0x43,
        LE_KC_D                 = 0x44,
        LE_KC_E                 = 0x45,
        LE_KC_F                 = 0x46,
        LE_KC_G                 = 0x47,
        LE_KC_H                 = 0x48,
        LE_KC_I                 = 0x49,
        LE_KC_J                 = 0x4A,
        LE_KC_K                 = 0x4B,
        LE_KC_L                 = 0x4C,
        LE_KC_M                 = 0x4D,
        LE_KC_N                 = 0x4E,
        LE_KC_O                 = 0x4F,
        LE_KC_P                 = 0x50,
        LE_KC_Q                 = 0x51,
        LE_KC_R                 = 0x52,
        LE_KC_S                 = 0x53,
        LE_KC_T                 = 0x54,
        LE_KC_U                 = 0x55,
        LE_KC_V                 = 0x56,
        LE_KC_W                 = 0x57,
        LE_KC_X                 = 0x58,
        LE_KC_Y                 = 0x59,
        LE_KC_Z                 = 0x5A,
        LE_KC_NUMPAD_0          = VK_NUMPAD0,
        LE_KC_NUMPAD_1          = VK_NUMPAD1,
        LE_KC_NUMPAD_2          = VK_NUMPAD2,
        LE_KC_NUMPAD_3          = VK_NUMPAD3,
        LE_KC_NUMPAD_4          = VK_NUMPAD4,
        LE_KC_NUMPAD_5          = VK_NUMPAD5,
        LE_KC_NUMPAD_6          = VK_NUMPAD6,
        LE_KC_NUMPAD_7          = VK_NUMPAD7,
        LE_KC_NUMPAD_8          = VK_NUMPAD8,
        LE_KC_NUMPAD_9          = VK_NUMPAD9,
        LE_KC_NUMPAD_MULTIPLY   = VK_MULTIPLY,
        LE_KC_NUMPAD_ADD        = VK_ADD,
        LE_KC_NUMPAD_ENTER      = VK_SEPARATOR,
        LE_KC_NUMPAD_SUBTRACT   = VK_SUBTRACT,
        LE_KC_NUMPAD_DIVIDE     = VK_DIVIDE,
        LE_KC_F1                = VK_F1,
        LE_KC_F2                = VK_F2,
        LE_KC_F3                = VK_F3,
        LE_KC_F4                = VK_F4,
        LE_KC_F5                = VK_F5,
        LE_KC_F6                = VK_F6,
        LE_KC_F7                = VK_F7,
        LE_KC_F8                = VK_F8,
        LE_KC_F9                = VK_F9,
        LE_KC_F10               = VK_F10,
        LE_KC_F11               = VK_F11,
        LE_KC_F12               = VK_F12,
        LE_KC_F13               = VK_F13,
        LE_KC_F14               = VK_F14,
        LE_KC_F15               = VK_F15,
        LE_KC_F16               = VK_F16,
        LE_KC_F17               = VK_F17,
        LE_KC_F18               = VK_F18,
        LE_KC_F19               = VK_F19,
        LE_KC_F20               = VK_F20,
        LE_KC_F21               = VK_F21,
        LE_KC_F22               = VK_F22,
        LE_KC_F23               = VK_F23,
        LE_KC_F24               = VK_F24,
        LE_KC_NUMLOCK           = VK_NUMLOCK,
        LE_KC_SCROLL            = VK_SCROLL
    };
}

#endif